apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  type: ClusterIP
  selector:
    app: redis-deployment
    #app: metrics
    #department: engineering
    #deployment: redis-deployment
  ports:
  - protocol: TCP
    #name: http-81
    port: 6379
    targetPort: 6379
    #nodePort: 31001
    # name: http-appmetrics# <protocol>[-<suffix>].
    # appProtocol: http # <protocol>
    # nodePort: 32225 #<30000 - 32767>

#  - protocol: TCP
#    name: http-2
#    port: 8080
#    targetPort: 8003
#    nodePort: 31446

# kubectl get nodes --output wide
# gcloud compute firewall-rules create test-node-port --allow tcp:node-port
# browser -> node-ip-address:node-port
#Â gcloud compute firewall-rules delete test-node-port