apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote 
  labels:
    app: result-deployment 
spec:
  selector:
    matchLabels:
      #app: metrics
      #department: engineering
      app: result-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: result-deployment
        #app: metrics
        #department: engineering
    spec:
      containers:
      - name: result
        image: "wjma90/examplevotingapp_result:before"
        ports:
        - containerPort: 80
          #name: http-81
        env:
        - name: "PORT"
          value: "80"
 #     - name: hello2
 #       image: "gcr.io/google-samples/hello-app:1.0"
 #       ports:
 #       - containerPort: 8003
 #         name: http-8003
 #       env:
 #       - name: "PORT"
 #         value: "8003"